# Generated by Django 5.0.2 on 2024-03-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('Acoustic', 'Acoustic'), ('Electric', 'Electric'), ('Bass', 'Bass'), ('Semi-Hollow', 'Semi-Hollow'), ('Hollow Body', 'Hollow'), ('Other', 'Other')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('short_description', models.TextField(null=True)),
            ],
        ),
    ]
