# Generated by Django 5.0.2 on 2024-03-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='short_description',
            field=models.TextField(blank=True, max_length=24, null=True),
        ),
    ]
