# Generated by Django 5.0.2 on 2024-03-06 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='guitar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='guitar.guitar'),
        ),
    ]
