version: '3.7'
services:
    web:
      image: kaanev/guitar_house
      build:
           context: .
           dockerfile: Dockerfile
      ports:
           - "8000:8000"
      env_file:
         - ./envs/.env
      volumes:
            - .:/app
      platform: linux/amd64
      command: gunicorn -b 0.0.0.0:8000 guitar_house.wsgi

    postgres:
      image: postgres
      restart: always
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=fuck_db
        - PGDATA=/var/lib/postgresql/data
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
    nginx:
      image: nginx
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf

